# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

builds:
  - id: macreleaser
    main: ./cmd/macreleaser
    binary: macreleaser
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/macreleaser/macreleaser/pkg/version.version={{.Version}}
      - -X github.com/macreleaser/macreleaser/pkg/version.commit={{.Commit}}
      - -X github.com/macreleaser/macreleaser/pkg/version.date={{.Date}}

archives:
  - id: macreleaser
    formats:
      - tar.gz

changelog:
  sort: asc
  filters:
    exclude:
      - "^test:"
      - "^chore:"
      - "Merge pull request"
  groups:
    - title: Features
      regexp: '^feat:'
    - title: Bug Fixes
      regexp: '^fix:'
    - title: Documentation
      regexp: '^docs:'
    - title: Other
      order: 999
